import type { CSSProperties } from 'react';
import { Link } from 'react-router';
import { CopyButton } from '../components/controls';
import { DownloadCards } from '../components/DownloadCards';
import { GithubMark, Icon } from '../components/icons';
import { OS_NAME, useOs, useRelease } from '../lib/hooks';
import { GITHUB, withBase } from '../lib/site';

const img = (name: string) => withBase(`/images/${name}`);
const mask = (m: string): CSSProperties => ({ WebkitMaskImage: m, maskImage: m });

const PROVIDERS = ['GitHub', 'GitLab', 'Bitbucket', 'Hugging Face', 'Azure DevOps', 'Codeberg', 'Gitea', 'SourceHut'];

const COMMANDS: [note: string, bin: string, rest: string][] = [
  ['who is active on each host', 'lanyard', ' status'],
  ['switch GitHub to the personal account', 'lanyard', ' use github personal'],
  ['clone through the work account', 'git', ' clone $(lanyard url github work https://github.com/acme/app)'],
  ['change the key a server uses', 'lanyard', ' hosts key prod id_ed25519_servers'],
  ['open an SSH session', 'lanyard', ' connect prod'],
];

const MANAGED: [comment: boolean, text: string][] = [
  [true, '# >>> lanyard managed section >>>'],
  [true, '# Generated by Lanyard. Change these entries from the app or the'],
  [true, '# `lanyard` CLI - manual edits inside this section are overwritten.'],
  [false, ''],
  [false, 'Host github.com'],
  [false, '    User git'],
  [false, '    IdentityFile ~/.ssh/id_ed25519_github_work'],
  [false, '    IdentitiesOnly yes'],
  [false, ''],
  [false, 'Host github.com-personal'],
  [false, '    HostName github.com'],
  [false, '    IdentityFile ~/.ssh/id_ed25519_github_personal'],
  [true, '# <<< lanyard managed section <<<'],
];
const YOURS: [comment: boolean, text: string][] = [
  [false, ''],
  [true, '# Your own entries'],
  [false, 'Host *'],
  [false, '    ServerAliveInterval 60'],
  [false, '    AddKeysToAgent yes'],
  [false, ''],
  [false, 'Host nas'],
  [false, '    HostName 192.168.1.40'],
  [false, '    User admin'],
];

const MINI_CARDS = [
  {
    title: 'SSH keys',
    text: 'Generate keys, add or change passphrases, and see which account or server uses each one.',
    img: 'keys.png',
    alt: 'Keys list with fingerprints and the accounts and hosts that use each key',
    crop: { width: '142.222%', margin: '-18.222% 0 0 -29.111%' },
  },
  {
    title: 'ssh-agent',
    text: 'See whether the agent is running and load keys into it, so a passphrase is asked for once.',
    img: 'overview.png',
    alt: 'Overview cards showing key count and ssh-agent status',
    crop: { width: '259.109%', margin: '-32.389% 0 0 -152.227%' },
  },
  {
    title: 'Known hosts',
    text: 'Scan a host and check its fingerprints before trusting it. Remove stale entries after a server is rebuilt.',
    img: 'scan-host.png',
    alt: 'Scan host keys dialog listing RSA, ECDSA and ED25519 fingerprints for gitlab.com',
    crop: { width: '164.103%', margin: '-29.487% 0 0 -32.051%' },
  },
  {
    title: 'Automatic backups',
    text: 'A snapshot of your config or known_hosts is taken before every change. Restore any of them in one click.',
    img: 'backups.png',
    alt: 'Backups list with timestamps next to the contents of the selected snapshot',
    crop: { width: '130.612%', margin: '-16.735% 0 0 -26.735%' },
  },
];

function Hero() {
  const release = useRelease();
  const os = useOs();
  const direct = os && release.assets[os === 'mac' ? 'macArm' : os];

  return (
    <section className="hero" id="top">
      <div
        className="deco deco-grid"
        aria-hidden="true"
        style={{
          inset: '0 0 30% 0',
          backgroundPosition: 'center top',
          ...mask('radial-gradient(ellipse 70% 80% at 50% 0%,#000 30%,transparent 75%)'),
        }}
      />
      <div
        className="deco"
        aria-hidden="true"
        style={{
          left: '50%',
          top: -240,
          width: 'min(1100px,140vw)',
          height: 560,
          transform: 'translateX(-50%)',
          background: 'radial-gradient(closest-side,var(--glow),transparent)',
          filter: 'blur(10px)',
        }}
      />
      <div className="container hero-inner">
        <div className="lanyard-strap" aria-hidden="true">
          <span />
          <span />
        </div>
        <a href={release.url} className="version-pill">
          <span className="tag">v{release.version}</span>
          <span>Free and open source, MIT license</span>
          <Icon name="arrow" size={14} />
        </a>
        <h1>
          <span>Wear the right identity</span>
          <span className="accent">everywhere.</span>
        </h1>
        <p className="hero-sub">
          Switch between accounts on GitHub, GitLab, Bitbucket, Hugging Face or any other git host in one click, and manage every server in
          your SSH config from one list.
        </p>
        <div className="hero-ctas">
          {direct ? (
            <a href={direct} className="btn btn-primary btn-lg">
              <Icon name="download" size={17} strokeWidth={2.2} />
              <span>Download for {OS_NAME[os]}</span>
            </a>
          ) : (
            <Link to="/download/" className="btn btn-primary btn-lg">
              <Icon name="download" size={17} strokeWidth={2.2} />
              <span>Download</span>
            </Link>
          )}
          <a href={GITHUB} className="btn btn-secondary btn-lg">
            <GithubMark />
            <span>View on GitHub</span>
          </a>
        </div>
        <p className="hero-note">
          <Link to="/download/">Other platforms</Link> · Windows, macOS and Linux
        </p>
      </div>
      <div className="hero-shot">
        <div
          className="deco"
          aria-hidden="true"
          style={{
            left: '8%',
            right: '8%',
            top: '12%',
            bottom: '-6%',
            background: 'radial-gradient(closest-side,var(--glow-strong),transparent)',
            filter: 'blur(40px)',
          }}
        />
        <div className="glass">
          <div className="window">
            <div className="window-bar">
              <span className="dot" />
              <span className="dot" />
              <span className="dot" />
              <span className="window-title">
                <img src={withBase('/icon.png')} alt="" width={14} height={14} />
                Lanyard
              </span>
            </div>
            <img
              className="only-light"
              src={img('overview-light.png')}
              alt="Lanyard overview: active git accounts per provider and the list of SSH servers"
              width={1280}
              height={800}
            />
            <img
              className="only-dark"
              src={img('overview.png')}
              alt="Lanyard overview: active git accounts per provider and the list of SSH servers"
              width={1280}
              height={800}
            />
          </div>
        </div>
      </div>
    </section>
  );
}

function Problem() {
  return (
    <section className="section" aria-labelledby="problem-h">
      <div
        className="deco deco-dots"
        aria-hidden="true"
        style={mask('radial-gradient(ellipse 55% 60% at 50% 30%,#000 10%,transparent 70%)')}
      />
      <div
        className="deco deco-glow"
        aria-hidden="true"
        style={{ left: '50%', top: '5%', width: 'min(800px,120vw)', height: 420, transform: 'translateX(-50%)' }}
      />
      <div className="container">
        <div style={{ textAlign: 'center', maxWidth: 820, margin: '0 auto' }}>
          <p className="eyebrow">THE PROBLEM</p>
          <h2 id="problem-h" className="h2" style={{ marginTop: 16 }}>
            Two GitHub accounts, one <span className="code-chip">git@github.com</span>
          </h2>
          <p className="lead" style={{ margin: '22px auto 0', maxWidth: '40em' }}>
            SSH offers whichever key it finds first. Pushes to a client repo fail, or go through under the wrong account with the wrong
            email on every commit.
          </p>
        </div>
        <div className="term-pair">
          <div className="term">
            <div className="term-head">
              <span className="led" />
              Without Lanyard
            </div>
            <pre>
              <span className="t-muted">$</span> git push{'\n'}
              <span className="t-danger">ERROR: Permission to acme/app.git denied to jane-personal.</span>
              {'\n'}
              <span className="t-danger">fatal: Could not read from remote repository.</span>
            </pre>
          </div>
          <div className="term is-good">
            <div className="term-head">
              <img src={withBase('/icon.png')} alt="" width={16} height={16} />
              With Lanyard
            </div>
            <pre>
              <span className="t-muted">$</span> <span className="t-accent">lanyard</span> use github work{'\n'}
              <span className="t-muted">$</span> git push{'\n'}
              <span className="t-muted">To github.com:acme/app.git</span>
              {'\n'}
              <span className="t-success">{'   3f2a1c9..8b4e0d2  main -> main'}</span>
            </pre>
          </div>
        </div>
        <p
          style={{
            margin: 'clamp(32px,4vw,48px) auto 0',
            maxWidth: '46em',
            textAlign: 'center',
            fontSize: 18,
            lineHeight: 1.6,
            textWrap: 'pretty',
          }}
        >
          Lanyard points{' '}
          <code className="inline-code" style={{ color: 'var(--accent-text)' }}>
            git@github.com
          </code>{' '}
          at the account you pick, sets the commit name and email to match, and gives each account its own alias host for the times you need
          both.
        </p>
      </div>
    </section>
  );
}

function GitAccounts() {
  return (
    <section id="features" className="section is-surface" aria-labelledby="git-h">
      <div
        className="deco deco-grid"
        aria-hidden="true"
        style={mask('radial-gradient(ellipse 50% 45% at 0% 0%,#000 10%,transparent 70%)')}
      />
      <div className="container">
        <div className="split">
          <h2 id="git-h" className="h2">
            Pick the account. Git follows.
          </h2>
          <div>
            <p className="lead">
              Add each account once with its own SSH key, name and email. Switching rewrites only what git needs, on any host you push to
              over SSH.
            </p>
            <ul className="providers" aria-label="Supported providers">
              {PROVIDERS.map((p) => (
                <li key={p}>{p}</li>
              ))}
              <li className="is-more">Self-hosted, or any git host over SSH</li>
            </ul>
          </div>
        </div>
        <div className="stage">
          <div
            className="deco deco-grid"
            aria-hidden="true"
            style={{ backgroundSize: '40px 40px', ...mask('radial-gradient(ellipse 80% 70% at 50% 0%,#000 20%,transparent 80%)') }}
          />
          <div className="deco deco-glow" aria-hidden="true" style={{ left: '15%', right: '15%', top: '10%', height: '70%' }} />
          <div className="shot-top">
            <img
              src={img('accounts.png')}
              alt="Git accounts screen: GitHub, GitLab and Hugging Face with the active account marked and its alias host"
              width={1280}
              height={800}
              loading="lazy"
            />
          </div>
        </div>
        <div className="cards" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,280px),1fr))' }}>
          <div className="card">
            <span className="icon-tile">
              <Icon name="switch" />
            </span>
            <h3>Switch in one click</h3>
            <p>
              Choose the active account per provider. Plain <code className="inline-code">git@github.com</code> URLs use its key, and
              commits carry its name and email.
            </p>
          </div>
          <div className="card">
            <span className="icon-tile">
              <Icon name="columns" />
            </span>
            <h3>Two accounts side by side</h3>
            <p>
              Every account also gets an alias host. Clone with <code className="inline-code">git@github.com-work</code> and that repo stays
              on work, whatever is active.
            </p>
          </div>
          <div className="card">
            <span className="icon-tile">
              <Icon name="pulse" />
            </span>
            <h3>Test before you push</h3>
            <p>Check each account against its provider and see which identity answers, before a push goes out under the wrong one.</p>
          </div>
        </div>
      </div>
    </section>
  );
}

function RemoteServers() {
  const cards = [
    {
      icon: 'terminal',
      title: 'Connect in one click',
      text: <>Open a terminal session on any server from the list, the palette or the tray.</>,
    },
    {
      icon: 'key',
      title: 'Switch keys per server',
      text: (
        <>
          Pick the IdentityFile for each host from the keys in <code className="inline-code">~/.ssh</code>.
        </>
      ),
    },
    { icon: 'jump', title: 'Jump hosts', text: <>Reach private machines through a bastion with ProxyJump or ProxyCommand.</> },
    {
      icon: 'shield',
      title: 'Trust host keys safely',
      text: <>Scan a server, compare its fingerprints with the published ones, then trust it.</>,
    },
  ] as const;

  return (
    <section className="section" aria-labelledby="ssh-h">
      <div
        className="deco deco-dots"
        aria-hidden="true"
        style={mask('radial-gradient(ellipse 50% 45% at 100% 0%,#000 10%,transparent 70%)')}
      />
      <div className="deco deco-glow" aria-hidden="true" style={{ right: '-10%', top: '-10%', width: 600, height: 400 }} />
      <div className="container">
        <div className="split">
          <h2 id="ssh-h" className="h2">
            Every server in{' '}
            <span className="mono" style={{ fontWeight: 700, fontSize: '.8em', letterSpacing: '-0.03em' }}>
              ~/.ssh/config
            </span>
            , in one list.
          </h2>
          <p className="lead">
            Lanyard reads the Host entries you already have. Edits keep your comments and formatting, and every change is backed up first.
          </p>
        </div>
        <div className="stage">
          <div
            className="deco deco-dots"
            aria-hidden="true"
            style={{ backgroundSize: '20px 20px', ...mask('radial-gradient(ellipse 80% 70% at 50% 0%,#000 20%,transparent 80%)') }}
          />
          <div className="deco deco-glow" aria-hidden="true" style={{ left: '10%', right: '10%', top: '10%', height: '70%' }} />
          <div className="stage-shots">
            <div className="shot-top">
              <img
                src={img('hosts.png')}
                alt="Hosts screen: servers with their target and the SSH key each one uses"
                width={1280}
                height={800}
                loading="lazy"
              />
            </div>
            <div className="shot-top">
              <img
                src={img('host-editor.png')}
                alt="Host editor dialog for prod-web: HostName, User, Port, IdentityFile and ProxyJump fields"
                width={1280}
                height={800}
                loading="lazy"
              />
            </div>
          </div>
        </div>
        <div className="cards" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,240px),1fr))' }}>
          {cards.map((c) => (
            <div className="card on-surface" key={c.title}>
              <span className="icon-tile">
                <Icon name={c.icon} />
              </span>
              <h3>{c.title}</h3>
              <p>{c.text}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function MoreTools() {
  return (
    <section className="section is-surface" aria-labelledby="more-h">
      <div
        className="deco deco-grid"
        aria-hidden="true"
        style={mask('radial-gradient(ellipse 70% 50% at 50% 100%,#000 10%,transparent 70%)')}
      />
      <div
        className="deco deco-glow"
        aria-hidden="true"
        style={{ left: '50%', bottom: '-20%', width: 'min(900px,120vw)', height: 420, transform: 'translateX(-50%)' }}
      />
      <div className="container">
        <h2 id="more-h" className="h2" style={{ maxWidth: 760 }}>
          Keys, agent, known hosts and backups.
        </h2>
        <div className="mini-cards">
          {MINI_CARDS.map((c) => (
            <article className="mini-card" key={c.title}>
              <div className="mini-card-text">
                <h3>{c.title}</h3>
                <p>{c.text}</p>
              </div>
              <div className="mini-card-shot">
                <div className="deco deco-grid" aria-hidden="true" />
                <div className="crop">
                  <img src={img(c.img)} alt={c.alt} loading="lazy" style={c.crop} />
                </div>
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}

function Everywhere() {
  return (
    <section className="section" aria-labelledby="ev-h">
      <div
        className="deco deco-dots"
        aria-hidden="true"
        style={mask('radial-gradient(ellipse 45% 60% at 0% 60%,#000 10%,transparent 70%)')}
      />
      <div className="deco deco-glow" aria-hidden="true" style={{ left: '-10%', top: '30%', width: 600, height: 420 }} />
      <div className="container two-col">
        <div>
          <h2 id="ev-h" className="h2">
            A shortcut away, from anywhere.
          </h2>
          <div className="feature-list">
            <div className="feature-row">
              <h3>System tray</h3>
              <p>Lanyard lives in the tray. Switch an account or connect to a server from its menu without opening the window.</p>
            </div>
            <div className="feature-row">
              <h3>
                Command palette
                <span className="keys-inline">
                  <kbd>Ctrl</kbd>
                  <kbd>K</kbd>
                </span>
                <span className="or">or</span>
                <span className="keys-inline">
                  <kbd>⌘</kbd>
                  <kbd>K</kbd>
                </span>
              </h3>
              <p>Type to find an account, a host or an action, then press Enter.</p>
            </div>
            <div className="feature-row">
              <h3>Keyboard first</h3>
              <p className="kbd-line">
                <kbd>↑</kbd>
                <kbd>↓</kbd>
                <span>to move,</span>
                <kbd>↵</kbd>
                <span>to run,</span>
                <kbd>esc</kbd>
                <span>to close.</span>
              </p>
            </div>
          </div>
        </div>
        <div className="stage-ring">
          <div
            className="deco"
            aria-hidden="true"
            style={{
              inset: 0,
              background: 'repeating-radial-gradient(circle at 50% 50%,transparent 0 46px,var(--grid) 46px 47px)',
              ...mask('radial-gradient(circle at 50% 50%,#000 30%,transparent 72%)'),
            }}
          />
          <div
            className="deco"
            aria-hidden="true"
            style={{ inset: '15%', background: 'radial-gradient(closest-side,var(--glow-strong),transparent)', filter: 'blur(30px)' }}
          />
          <div className="window" style={{ background: '#17181c' }}>
            <div style={{ aspectRatio: '644/500', overflow: 'hidden' }}>
              <img
                src={img('palette.png')}
                alt="Command palette with sections for switching accounts, connecting to hosts and running actions"
                loading="lazy"
                style={{ display: 'block', width: '198.758%', maxWidth: 'none', margin: '-21.429% 0 0 -49.379%' }}
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function Cli() {
  return (
    <section id="cli" className="section is-surface" aria-labelledby="cli-h">
      <div
        className="deco deco-grid"
        aria-hidden="true"
        style={mask('radial-gradient(ellipse 60% 70% at 85% 50%,#000 10%,transparent 70%)')}
      />
      <div className="container two-col">
        <div>
          <h2 id="cli-h" className="h2">
            Everything, from the terminal.
          </h2>
          <p className="lead" style={{ marginTop: 20 }}>
            The app and the <code className="inline-code">lanyard</code> CLI share the same config, so scripts and the window always agree.{' '}
            <code className="inline-code">lny</code> is the short alias.
          </p>
          <div className="install-list">
            {[
              ['Install globally', 'npm install -g lanyard-ssh'],
              ['Or run without installing', 'npx lanyard-ssh status'],
            ].map(([label, cmd]) => (
              <div key={cmd}>
                <p className="install-label">{label}</p>
                <div className="install-box">
                  <code>
                    <span className="t-muted">$ </span>
                    {cmd}
                  </code>
                  <CopyButton text={cmd} label="Copy" />
                </div>
              </div>
            ))}
          </div>
        </div>
        <div style={{ position: 'relative' }}>
          <div
            className="deco"
            aria-hidden="true"
            style={{
              inset: '10% 5% -5%',
              background: 'radial-gradient(closest-side,var(--glow-strong),transparent)',
              filter: 'blur(40px)',
            }}
          />
          <div className="terminal">
            <div className="terminal-head">
              <span className="dot" />
              <span className="dot" />
              <span className="dot" />
              <span className="cwd">~/code</span>
              <CopyButton text={COMMANDS.map(([, b, r]) => b + r).join('\n')} label="Copy all" icon={false} aria="Copy all commands" />
            </div>
            <div className="terminal-body">
              {COMMANDS.map(([note, bin, rest]) => (
                <div className="cmd" key={note}>
                  <div className="cmd-text">
                    <div className="t-muted"># {note}</div>
                    <div>
                      <span className="t-muted">$ </span>
                      <span className="t-accent">{bin}</span>
                      {rest}
                    </div>
                  </div>
                  <CopyButton text={bin + rest} />
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function ManagedSection() {
  return (
    <section className="section" aria-labelledby="cfg-h">
      <div
        className="deco deco-grid"
        aria-hidden="true"
        style={mask('radial-gradient(ellipse 50% 60% at 100% 50%,#000 10%,transparent 70%)')}
      />
      <div className="container two-col">
        <div>
          <h2 id="cfg-h" className="h2">
            One marked block. The rest is untouched.
          </h2>
          <p className="lead" style={{ marginTop: 20 }}>
            Lanyard writes its entries between two marker comments in <code className="inline-code">~/.ssh/config</code>. Everything outside
            them stays exactly as you wrote it.
          </p>
          <ul className="trust-list">
            <li>
              <span className="icon-tile">
                <Icon name="history" size={16} />
              </span>
              <div>
                <strong>Backups before every change</strong>
                <p>Your config and known_hosts are snapshotted before each write, and any snapshot can be restored.</p>
              </div>
            </li>
            <li>
              <span className="icon-tile">
                <Icon name="chip" size={16} />
              </span>
              <div>
                <strong>Locked-down window</strong>
                <p>
                  The app's window has no access to your files and can only call Lanyard's own API. The source is on GitHub for anyone to
                  review.
                </p>
              </div>
            </li>
            <li>
              <span className="icon-tile">
                <Icon name="lock" size={16} />
              </span>
              <div>
                <strong>Passphrases never stored</strong>
                <p>They go straight to OpenSSH and are never saved by Lanyard.</p>
              </div>
            </li>
          </ul>
        </div>
        <div style={{ position: 'relative' }}>
          <div className="deco deco-glow" aria-hidden="true" style={{ inset: '0 10% 40%', filter: 'blur(40px)' }} />
          <div className="terminal">
            <div className="file-head">
              <Icon name="file" size={14} />
              ~/.ssh/config
            </div>
            <div className="cfg">
              {MANAGED.map(([comment, text], i) => (
                <div className="cfg-line is-managed" key={`m${i}`}>
                  <span className="cfg-tag" aria-hidden="true">
                    {i === 0 ? 'Lanyard' : ''}
                  </span>
                  <span className={`cfg-text${comment ? ' is-comment' : ''}`}>{text || ' '}</span>
                </div>
              ))}
              {YOURS.map(([comment, text], i) => (
                <div className="cfg-line" key={`y${i}`}>
                  <span className="cfg-tag" aria-hidden="true">
                    {i === 1 ? 'Yours' : ''}
                  </span>
                  <span className={`cfg-text${comment ? ' is-comment' : ''}`}>{text || ' '}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function Download() {
  const release = useRelease();
  return (
    <section id="download" className="section is-surface" aria-labelledby="dl-h" style={{ padding: 'clamp(96px,12vw,160px) 0' }}>
      <div
        className="deco deco-grid"
        aria-hidden="true"
        style={{ backgroundPosition: 'center top', ...mask('radial-gradient(ellipse 60% 55% at 50% 0%,#000 20%,transparent 75%)') }}
      />
      <div
        className="deco"
        aria-hidden="true"
        style={{
          left: '50%',
          top: -200,
          width: 'min(900px,140vw)',
          height: 520,
          transform: 'translateX(-50%)',
          background: 'radial-gradient(closest-side,var(--glow),transparent)',
          filter: 'blur(10px)',
        }}
      />
      <div className="container">
        <div className="dl-head">
          <img src={withBase('/icon.png')} alt="" width={80} height={80} />
          <h2 id="dl-h">Free for Windows, macOS and Linux.</h2>
          <p>
            <span className="mono" style={{ color: 'var(--text)' }}>
              v{release.version}
            </span>{' '}
            · MIT license · <a href={release.url}>Release notes</a>
          </p>
        </div>
        <DownloadCards />
      </div>
    </section>
  );
}

export function Home() {
  return (
    <>
      <Hero />
      <Problem />
      <GitAccounts />
      <RemoteServers />
      <MoreTools />
      <Everywhere />
      <Cli />
      <ManagedSection />
      <Download />
    </>
  );
}
